// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuupeinekiabdxuwbsao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dXBlaW5la2lhYmR4dXdic2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODg2MjQsImV4cCI6MjA2ODY2NDYyNH0.y-nfZWWEB_oDALrL65V48yD9sdimssFXKsKo2TpRvdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});